org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=26.3
neoforge_version=26.3.0.7-beta
moddevgradle_version=2.0.147
java_version=25

mod_version=1.7
maven_group=org.sawiq
archives_base_name=pv-voice-changer-neoforge
mod_id=pv_voice_changer

pv_version=neoforge-26.3-2.1.17
pv_dependency_version=2.1.17
