# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
# Mod Properties
mod_version=1.7.4
maven_group=org.sawiq
archives_base_name=pv-voice-changer
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.161.0+26.3
pv_version=fabric-26.3-2.1.17
